# Datenstrom Yellow extension settings

Extension: Maintain
Version: 0.9.11
Description: Make and maintain extensions.
Developer: Anna Svensson
Tag: feature
DownloadUrl: https://github.com/annaesvensson/yellow-maintain/archive/refs/heads/main.zip
DocumentationUrl: https://github.com/annaesvensson/yellow-maintain
DocumentationLanguage: en, de, sv
Published: 2026-09-08 17:32:39
Status: maintained
system/workers/maintain.php: maintain.php, create, update
